CARD_NEGATIVE_EDITION = 'negative'
CARD_FOIL_EDITION = 'foil'
CARD_POLYCHROME_EDITION = 'polychrome'
CARD_HOLOGRAPHIC_EDITION = 'holographic'

CARD_EDITIONS = [
    CARD_NEGATIVE_EDITION,
    CARD_FOIL_EDITION,
    CARD_POLYCHROME_EDITION,
    CARD_HOLOGRAPHIC_EDITION,
]
